### ISSUE TITLE
Question: What are the differences between this and `stream-broadcast`?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [nikis05/fork_stream#1]
It seems to me like this crate is kind of similar to [`stream-broadcast`](https://crates.io/crates/stream-broadcast).
- In what scenarios is it better to use `stream-broadcast`?
- In what scenarios is it better to use `fork-stream`?

**Comment by nikis05** [comment]
The libraries are almost completely identical, I haven't found stream-broadcast until after I finished implementing this one 😅 The only real difference is that `stream-broadcast` supports setting a size limit on the amount of cached items, which may be important if you don't want your cache size to grow out of control.

Also I may be wrong but I think there is a minor bug in `stream-broadcast`, where it wakes the stream forks all at the same time, which will make them try to lock the same mutex simultaneously. So a poll will block which it shouldn't.
