### ISSUE TITLE
Can I fork tcpstream?

### ISSUE THREAD

**Issue by YDHCUI** [nikis05/fork_stream#2]
I'm getting an error trying to fork tcpstream

![1718344829660](https://github.com/nikis05/fork_stream/assets/46884495/8dd0c4e9-bebc-443d-abba-5e772dfc8d61)

**Comment by nikis05** [comment]
Looks like the stream that you are trying to fork doesn't implement `futures::Stream`. Looks like there is no bound `<T as Transport::RawStream: futures::Stream>`. If `Transport` trait comes from your crate, consider adding a bound on the associated type.
